//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lindsey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int TicketId { get; set; }
        public decimal Price { get; set; }
        public int ResortID { get; set; }
        public int TicketTypeID { get; set; }
    
        public virtual TicketType TicketType { get; set; }
        public virtual Resort Resort { get; set; }
    }
}
